In [8]:
import numpy as np
from pyannote.core import SlidingWindow, SlidingWindowFeature
from pyannote.core import Segment

initial_feat = SlidingWindowFeature(np.arange(0,10).reshape((10,1)), sliding_window=SlidingWindow(0.5, 0.5, 0, 10))

In [9]:
initial_feat.crop(Segment(3,7))

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [23]:
other_feat = SlidingWindowFeature(np.arange(0,100).reshape(100, 1), sliding_window=SlidingWindow(1/3, 1/3, 0, 10))

In [24]:
list(initial_feat.align(other_feat).iterfeatures(True))

[(array([0.]), <Segment(0, 0.333333)>),
 (array([0.5]), <Segment(0.333333, 0.666667)>),
 (array([1.16666667]), <Segment(0.666667, 1)>),
 (array([1.83333333]), <Segment(1, 1.33333)>),
 (array([2.5]), <Segment(1.33333, 1.66667)>),
 (array([3.16666667]), <Segment(1.66667, 2)>),
 (array([3.83333333]), <Segment(2, 2.33333)>),
 (array([4.5]), <Segment(2.33333, 2.66667)>),
 (array([5.16666667]), <Segment(2.66667, 3)>),
 (array([5.83333333]), <Segment(3, 3.33333)>),
 (array([6.5]), <Segment(3.33333, 3.66667)>),
 (array([7.16666667]), <Segment(3.66667, 4)>),
 (array([7.83333333]), <Segment(4, 4.33333)>),
 (array([8.5]), <Segment(4.33333, 4.66667)>),
 (array([9.]), <Segment(4.66667, 5)>),
 (array([9.]), <Segment(5, 5.33333)>),
 (array([9.]), <Segment(5.33333, 5.66667)>),
 (array([9.]), <Segment(5.66667, 6)>),
 (array([9.]), <Segment(6, 6.33333)>),
 (array([9.]), <Segment(6.33333, 6.66667)>),
 (array([9.]), <Segment(6.66667, 7)>),
 (array([9.]), <Segment(7, 7.33333)>),
 (array([9.]), <Segment(7.3

In [26]:
np.arange(0,10).

(10, 1)